// =============================================================================
// Database Types
// =============================================================================
// Generated by: npm run db:generate-types
// Regenerate after schema changes: supabase gen types typescript --local > src/types/database.types.ts
//
// DO NOT EDIT THIS FILE MANUALLY — run the generate command instead.
// =============================================================================

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          subscription_status: "free" | "active" | "canceled" | "past_due" | "trialing";
          subscription_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_status?: "free" | "active" | "canceled" | "past_due" | "trialing";
          subscription_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          subscription_status?: "free" | "active" | "canceled" | "past_due" | "trialing";
          subscription_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          system_prompt: string | null;
          total_input_tokens: number;
          total_output_tokens: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title?: string;
          system_prompt?: string | null;
          total_input_tokens?: number;
          total_output_tokens?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          system_prompt?: string | null;
          total_input_tokens?: number;
          total_output_tokens?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          user_id: string;
          role: "user" | "assistant" | "tool";
          content: string;
          tool_name: string | null;
          tool_input: Json | null;
          tool_result: Json | null;
          input_tokens: number | null;
          output_tokens: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          user_id: string;
          role: "user" | "assistant" | "tool";
          content: string;
          tool_name?: string | null;
          tool_input?: Json | null;
          tool_result?: Json | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          user_id?: string;
          role?: "user" | "assistant" | "tool";
          content?: string;
          tool_name?: string | null;
          tool_input?: Json | null;
          tool_result?: Json | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          created_at?: string;
        };
      };
      notes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content: string;
          tags: string[];
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          content?: string;
          tags?: string[];
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          content?: string;
          tags?: string[];
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      usage_tracking: {
        Row: {
          id: string;
          user_id: string;
          conversation_id: string | null;
          message_id: string | null;
          model: string;
          input_tokens: number;
          output_tokens: number;
          estimated_cost_cents: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          conversation_id?: string | null;
          message_id?: string | null;
          model: string;
          input_tokens: number;
          output_tokens: number;
          estimated_cost_cents: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          conversation_id?: string | null;
          message_id?: string | null;
          model?: string;
          input_tokens?: number;
          output_tokens?: number;
          estimated_cost_cents?: number;
          created_at?: string;
        };
      };
    };
    Views: {
      monthly_usage: {
        Row: {
          user_id: string | null;
          month: string | null;
          message_count: number | null;
          total_input_tokens: number | null;
          total_output_tokens: number | null;
          total_cost_cents: number | null;
        };
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
